### ISSUE TITLE
~morewaita~ neowaita active and maintained  

### ISSUE THREAD

**Issue by iaacornus** [MoreWaita-Dev/MoreWaita#1]
MoreWaita's original repo, somepaulo/MoreWaita, had not shown any activities for several months. I'm assuming the repo is dead, thus the existence of this fork. This fork attempts to revive and further develop MoreWaita icon theme. All the issues and pull requests will be dealt herewithin.

**Comment by somepaulo** [comment]
Please rename this fork to stop confusion. The Arch morewaita-git package has already been switched to your repo, and now I can't even uodate my own install without editing the PKGBUILD because the maintainer is being a bit stubborn.

The original MoreWaita is in offline development due to refactoring that was breaking things for me until recently. This fork does not replace MoreWaita. v47 of the original MoreWaita should be coming out in about 10 days' time.

**Comment by iaacornus** [comment]
> Please rename this fork to stop confusion. The Arch morewaita-git package has already been switched to your repo, and now I can't even uodate my own install without editing the PKGBUILD because the maintainer is being a bit stubborn.
> 
> The original MoreWaita is in offline development due to refactoring that was breaking things for me until recently. This fork does not replace MoreWaita. v47 of the original MoreWaita should be coming out in about 10 days' time.

yes. It will be renamed sooned. We're currently looking up for more vialabe name that suits the fork's philosophy and planned path, refer to #21 .

**Comment by iaacornus** [comment]
> Please rename this fork to stop confusion. The Arch morewaita-git package has already been switched to your repo, and now I can't even uodate my own install without editing the PKGBUILD because the maintainer is being a bit stubborn.

but please do the community a favor. maybe try leaving a note sometimes or somehow respond even a little bit like "ok" or even "." to issues or prs just to indicate even the faintest heart beat of a project if u dont want it to be continued or taken over by others.

> The original MoreWaita is in offline development due to refactoring that was breaking things for me until recently. This fork does not replace MoreWaita. v47 of the original MoreWaita should be coming out in about 10 days' time.

if so, it would help that u put something like in readme which u can do even in github.com in a nokia 210. it would help for some people to not assume that the project is not dead even it does not receive any commit, response or anything in over almost half a year. thanks.

**Comment by somepaulo** [comment]
Thank you!  
You can still keep MoreWaita in the name if you wish. Just add something to it. Nerd, for example. Like 'nerd' versions of popular fonts. MoreWaita Nerd. Just a suggestion, of course.

**Comment by iaacornus** [comment]
> Thank you! You can still keep MoreWaita in the name if you wish. Just add something to it. Nerd, for example. Like 'nerd' versions of popular fonts. MoreWaita Nerd. Just a suggestion, of course.

well, it would have a different path and philosophy, so i think renaming it as you suggested will be the best course. as of now, we are deciding for a name and will settle it as soon as possible. rest assured that i'll ask the maintainer of aur package to redirect it to your original repo and we'll have a different package for this icon theme. Regardless of all issues, you did an impressive work in improving adwaita icon theme and we appreciate it. this fork will not exist without it, so cheers! i'm closing this issue now as this won't be "morewaita actively maintained" anymore

**Comment by somepaulo** [comment]
> please do the community a favor

It's been a hard few months, but you're right. There's been new commits to the repo though.

> it would help that u put something

Will do

> we'll have a different package for this icon theme

Let me know if you need help with the AUR packages. Happy to lend a hand. 

Thank you for your words if appreciation. I appreciate your effort and attitude too. Best of luck with your new endeavour! Looking forward to checking out the differences. 

PS  
One word of technical advice. I've noticed in a few merge requests that people make identical files for different versions of the same icon name. To keep things minimal, the best way is to have one actual filename and symlinks to it for the different version names. And the symlinks should be created from within the folder of the target file using only file names without any paths. Otherwise paths get hardcoded in the symlink and break installations.

Cheers, mate!

**Comment by somepaulo** [comment]
Neowaita is a cool name, btw 👍

**Comment by iaacornus** [comment]
> > please do the community a favor
> 
> It's been a hard few months, but you're right. There's been new commits to the repo though.
> 
> > it would help that u put something
> 
> Will do
> 
> > we'll have a different package for this icon theme
> 
> Let me know if you need help with the AUR packages. Happy to lend a hand.
> 
> Thank you for your words of appreciation. I appreciate your effort and attitude too. Best of luck with your new endeavour! Looking forward to checking out the differences.
> 
> PS One word of technical advice. I've noticed in a few merge requests that people make identical files for different versions of the same icon name. To keep things minimal, the best way is to have one actual file and symlinks to it for the different version names. And the symlinks should be created from within the folder of the target file using only file names without any paths. Otherwise paths get hardcoded in the symlink and break installations.
> 
> Cheers, mate!
> 
> (Edit: typos)

thank you for all of those suggestions, I'll be sure to take note of them. 

> Neowaita is a cool name, btw

it is decided then. it will be neowaita from now on.
